### ISSUE TITLE
Lets chatapp crash

### ISSUE THREAD

**Issue by tashish24** [Pradyuman7/LetsChat#2]
After registration it is not going ahead the app keeps on crashing after registration what should i do? Reply asap..

**Comment by Pradyuman7** [comment]
@tashish24 Can you give more info? What is the exception that you're getting? I can't really see what's happening without that.

**Comment by vanshikasahgal** [comment]
Yeah right, the app is getting crashed beyond the regsitration

**Comment by mukul-prabhakar** [comment]
resloved this issue please check the new merge request
